// A tracked doc may only link to something that is also tracked.
//
// This is the gate for a rule that spent months as prose, and the repo's own
// survey had already named the pattern: the rules being violated are the ones
// nothing checks.
//
// The failure it prevents is quiet and total. `spec/` and `qa/` are gitignored
// on purpose — planning notes and raw QA logs quote real ids, real paths and
// occasionally real credentials, and this is a public repo with permanent
// history. But nothing stopped a TRACKED file from linking into them, so five
// of them did: AGENTS.md, three files under rules/, and the web panel README
// all pointed at a survey and at ADRs that were never pushed. Locally every
// link worked. On GitHub, and in every fresh clone, all six were 404s — and
// the five ADRs behind them were architecture decisions no outside reader
// could see. Run against 8a244b5 (the commit before that was repaired) this
// test fails with exactly those six.
//
// Tracked-ness is the right assertion rather than "the file exists": existence
// passes on the machine that wrote the link, which is precisely the machine
// that will never notice. It also catches the ordinary broken relative path
// for free — this file's own first draft shipped `../AGENTS.md` from
// rules/workflow/, one level short.
//
// Excluded: docs/ (the Astro site links absolutely, `/apx/…`, and its own
// build validates them) and CHANGELOG.md (generated by semantic-release).

import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const REPO = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");

/** Every path git tracks, repo-relative and posix-separated. */
const tracked = new Set(
  execSync("git ls-files", { cwd: REPO, encoding: "utf8", maxBuffer: 1e8 })
    .split("\n")
    .filter(Boolean)
);

const trackedDirs = new Set();
for (const f of tracked) {
  let dir = path.posix.dirname(f);
  while (dir && dir !== ".") {
    trackedDirs.add(dir);
    dir = path.posix.dirname(dir);
  }
}

const docs = [...tracked].filter(
  (f) => f.endsWith(".md") && !f.startsWith("docs/") && f !== "CHANGELOG.md"
);

// [text](target) and [text](target "title"). Bare autolinks carry no path.
const LINK = /\[[^\]]*\]\(([^)\s]+)(?:\s+"[^"]*")?\)/g;

/** Repo-relative link targets in `file`, anchors and external schemes dropped. */
function linksIn(file) {
  const src = fs.readFileSync(path.join(REPO, file), "utf8");
  const out = [];
  for (const m of src.matchAll(LINK)) {
    const raw = m[1].trim();
    if (!raw || /^(https?:|mailto:|tel:|data:|#)/i.test(raw)) continue;
    let target;
    try {
      target = decodeURIComponent(raw.split("#")[0].split("?")[0]);
    } catch {
      target = raw.split("#")[0].split("?")[0]; // malformed %-escape: judge it raw
    }
    if (!target) continue;
    const resolved = path.posix
      .normalize(path.posix.join(path.posix.dirname(file), target))
      .replace(/\/$/, "");
    out.push({ raw, resolved });
  }
  return out;
}

test("every link in a tracked doc points at something tracked too", () => {
  const dead = [];
  for (const file of docs) {
    for (const { raw, resolved } of linksIn(file)) {
      if (tracked.has(resolved) || trackedDirs.has(resolved)) continue;
      const why = fs.existsSync(path.join(REPO, resolved))
        ? "exists locally but is NOT tracked — gitignored, or never added"
        : "does not exist";
      dead.push(`  ${file} -> ${raw}\n      resolves to ${resolved} — ${why}`);
    }
  }
  assert.equal(
    dead.length,
    0,
    `dead link(s) in tracked docs — these 404 on GitHub and in every fresh clone:\n${dead.join(
      "\n"
    )}\n\nPlanning lives in spec/ and QA in qa/; both are gitignored, so a tracked ` +
      `file must not link into them. Move the durable part into rules/, or drop the link.`
  );
});

test("the link check is not vacuous", () => {
  // A broken regex here would fail silently by finding nothing to check, which
  // reads as "all clear". Pin the floor so the gate cannot quietly stop gating.
  const files = docs.filter((f) => linksIn(f).length > 0);
  const total = docs.reduce((n, f) => n + linksIn(f).length, 0);
  assert.ok(docs.length >= 40, `only ${docs.length} tracked docs discovered`);
  assert.ok(total >= 80, `only ${total} relative links found — is LINK still right?`);
  assert.ok(files.length >= 10, `only ${files.length} docs carried a link`);
});
