// AUTO-GENERATED by scripts/export_web_assets.py — do not edit by hand.
// Blob avatar preset keys, for the non-browser surfaces that create agents
// (CLI, MCP server, daemon API). The renderer's copy — with eye rects and
// image sources — is src/interfaces/web/src/components/agents/blobPresets.ts.

export const BLOB_KEYS = Object.freeze([
  "menta",
  "parche",
  "trino",
  "cubi",
  "nimbo",
  "papa",
  "noche",
  "kiwi",
  "gajo",
  "campana",
  "cobalto",
  "rubi",
  "trebol",
  "saturno",
  "onyx",
]);
