// AUTO-GENERATED by scripts/export_web_assets.py — do not edit by hand.
// Square blob bodies live in public/modules/blobs/<key>.png; eye rects are in the
// same 256x256 canvas and are drawn animated on top by <BlobAvatar>. An empty eye
// list = a 'cyclops' whose face is baked into the render (it bobs but doesn't blink).

export type BlobEye = { x: number; y: number; w: number; h: number; rx: number };
export type BlobPreset = { key: string; label: string; src: string; eyeColor: string; eyes: BlobEye[] };

export const BLOB_VIEWBOX = 256;

export const BLOB_PRESETS: Record<string, BlobPreset> = {
  menta: { key: "menta", label: "Menta", src: "/modules/blobs/menta.png", eyeColor: "#15181C", eyes: [{ x: 105.0, y: 93.1, w: 16.0, h: 33.8, rx: 6.4 }, { x: 135.0, y: 93.1, w: 16.0, h: 33.8, rx: 6.4 }] },
  parche: { key: "parche", label: "Parche", src: "/modules/blobs/parche.png", eyeColor: "#15181C", eyes: [{ x: 119.4, y: 88.6, w: 17.3, h: 33.8, rx: 6.9 }, { x: 151.9, y: 88.6, w: 17.3, h: 33.8, rx: 6.9 }] },
  trino: { key: "trino", label: "Trino", src: "/modules/blobs/trino.png", eyeColor: "#15181C", eyes: [{ x: 105.5, y: 130.1, w: 18.0, h: 29.7, rx: 7.2 }, { x: 141.5, y: 130.1, w: 18.0, h: 29.7, rx: 7.2 }] },
  cubi: { key: "cubi", label: "Cubi", src: "/modules/blobs/cubi.png", eyeColor: "#15181C", eyes: [{ x: 103.2, y: 93.1, w: 17.2, h: 33.8, rx: 6.9 }, { x: 135.6, y: 93.1, w: 17.2, h: 33.8, rx: 6.9 }] },
  nimbo: { key: "nimbo", label: "Nimbo", src: "/modules/blobs/nimbo.png", eyeColor: "#15181C", eyes: [{ x: 103.3, y: 93.1, w: 17.1, h: 33.8, rx: 6.9 }, { x: 135.6, y: 93.1, w: 17.1, h: 33.8, rx: 6.9 }] },
  papa: { key: "papa", label: "Papa", src: "/modules/blobs/papa.png", eyeColor: "#15181C", eyes: [{ x: 105.2, y: 90.9, w: 18.5, h: 30.5, rx: 7.4 }, { x: 141.3, y: 90.9, w: 18.5, h: 30.5, rx: 7.4 }] },
  noche: { key: "noche", label: "Noche", src: "/modules/blobs/noche.png", eyeColor: "#3AE7B0", eyes: [{ x: 105.0, y: 133.6, w: 15.9, h: 33.8, rx: 6.4 }, { x: 138.8, y: 133.6, w: 15.9, h: 33.8, rx: 6.4 }] },
  kiwi: { key: "kiwi", label: "Kiwi", src: "/modules/blobs/kiwi.png", eyeColor: "#15181C", eyes: [{ x: 109.1, y: 84.1, w: 13.1, h: 29.3, rx: 5.2 }, { x: 133.8, y: 84.1, w: 13.1, h: 29.3, rx: 5.2 }] },
  gajo: { key: "gajo", label: "Gajo", src: "/modules/blobs/gajo.png", eyeColor: "#15181C", eyes: [{ x: 107.9, y: 95.3, w: 16.6, h: 29.3, rx: 6.7 }, { x: 139.3, y: 95.3, w: 16.6, h: 29.3, rx: 6.7 }] },
  campana: { key: "campana", label: "Campana", src: "/modules/blobs/campana.png", eyeColor: "#15181C", eyes: [{ x: 108.6, y: 86.3, w: 15.8, h: 29.3, rx: 6.3 }, { x: 135.5, y: 86.3, w: 15.8, h: 29.3, rx: 6.3 }] },
  cobalto: { key: "cobalto", label: "Cobalto", src: "/modules/blobs/cobalto.png", eyeColor: "#15181C", eyes: [{ x: 107.7, y: 95.3, w: 16.8, h: 29.3, rx: 6.7 }, { x: 139.4, y: 95.3, w: 16.8, h: 29.3, rx: 6.7 }] },
  rubi: { key: "rubi", label: "Rubí", src: "/modules/blobs/rubi.png", eyeColor: "#15181C", eyes: [] },
  trebol: { key: "trebol", label: "Trébol", src: "/modules/blobs/trebol.png", eyeColor: "#15181C", eyes: [{ x: 102.6, y: 120.1, w: 17.2, h: 29.3, rx: 6.9 }, { x: 134.1, y: 120.1, w: 17.2, h: 29.3, rx: 6.9 }] },
  saturno: { key: "saturno", label: "Saturno", src: "/modules/blobs/saturno.png", eyeColor: "#15181C", eyes: [] },
  onyx: { key: "onyx", label: "Onyx", src: "/modules/blobs/onyx.png", eyeColor: "#3AE7B0", eyes: [{ x: 96.3, y: 124.6, w: 16.6, h: 29.3, rx: 6.6 }, { x: 129.5, y: 124.6, w: 16.6, h: 29.3, rx: 6.6 }] },
  perla: { key: "perla", label: "Perla", src: "/modules/blobs/perla.png", eyeColor: "#15181C", eyes: [{ x: 100.6, y: 83.5, w: 14.9, h: 21.4, rx: 6.0 }, { x: 130.5, y: 83.5, w: 14.9, h: 21.4, rx: 6.0 }] },
  faro: { key: "faro", label: "Faro", src: "/modules/blobs/faro.png", eyeColor: "#15181C", eyes: [{ x: 91.7, y: 99.8, w: 15.4, h: 20.3, rx: 6.2 }, { x: 122.5, y: 99.8, w: 15.4, h: 20.3, rx: 6.2 }] },
  brasa: { key: "brasa", label: "Brasa", src: "/modules/blobs/brasa.png", eyeColor: "#15181C", eyes: [{ x: 94.8, y: 95.2, w: 16.9, h: 18.6, rx: 6.8 }, { x: 126.3, y: 95.2, w: 16.9, h: 18.6, rx: 6.8 }] },
  aqua: { key: "aqua", label: "Aqua", src: "/modules/blobs/aqua.png", eyeColor: "#15181C", eyes: [{ x: 92.9, y: 81.8, w: 10.9, h: 20.3, rx: 4.4 }, { x: 114.7, y: 81.8, w: 10.9, h: 20.3, rx: 4.4 }] },
  coral: { key: "coral", label: "Coral", src: "/modules/blobs/coral.png", eyeColor: "#15181C", eyes: [{ x: 99.4, y: 141.0, w: 14.5, h: 19.1, rx: 5.8 }, { x: 129.3, y: 141.0, w: 14.5, h: 19.1, rx: 5.8 }] },
  zafiro: { key: "zafiro", label: "Zafiro", src: "/modules/blobs/zafiro.png", eyeColor: "#15181C", eyes: [{ x: 102.9, y: 103.8, w: 16.1, h: 21.4, rx: 6.4 }, { x: 132.8, y: 103.8, w: 16.1, h: 21.4, rx: 6.4 }] },
  pino: { key: "pino", label: "Pino", src: "/modules/blobs/pino.png", eyeColor: "#15181C", eyes: [{ x: 109.1, y: 108.9, w: 15.6, h: 20.3, rx: 6.2 }, { x: 140.2, y: 108.9, w: 15.6, h: 20.3, rx: 6.2 }] },
  eclipse: { key: "eclipse", label: "Eclipse", src: "/modules/blobs/eclipse.png", eyeColor: "#060709", eyes: [{ x: 102.1, y: 102.9, w: 15.8, h: 18.1, rx: 6.3 }, { x: 131.4, y: 102.9, w: 15.8, h: 18.1, rx: 6.3 }] },
  peon: { key: "peon", label: "Peón", src: "/modules/blobs/peon.png", eyeColor: "#15181C", eyes: [{ x: 106.2, y: 73.9, w: 11.9, h: 18.0, rx: 4.8 }, { x: 133.9, y: 73.9, w: 11.9, h: 18.0, rx: 4.8 }] },
  ovni: { key: "ovni", label: "Ovni", src: "/modules/blobs/ovni.png", eyeColor: "#15181C", eyes: [{ x: 106.6, y: 105.0, w: 15.8, h: 16.0, rx: 6.3 }, { x: 138.1, y: 105.0, w: 15.8, h: 16.0, rx: 6.3 }] },
  amatista: { key: "amatista", label: "Amatista", src: "/modules/blobs/amatista.png", eyeColor: "#15181C", eyes: [{ x: 85.8, y: 103.4, w: 16.9, h: 18.3, rx: 6.8 }, { x: 117.3, y: 103.4, w: 16.9, h: 18.3, rx: 6.8 }] },
  volcan: { key: "volcan", label: "Volcán", src: "/modules/blobs/volcan.png", eyeColor: "#15181C", eyes: [{ x: 100.6, y: 73.4, w: 13.4, h: 19.1, rx: 5.4 }, { x: 127.5, y: 73.4, w: 13.4, h: 19.1, rx: 5.4 }] },
  quad: { key: "quad", label: "Quad", src: "/modules/blobs/quad.png", eyeColor: "#15181C", eyes: [{ x: 80.9, y: 68.2, w: 17.6, h: 21.8, rx: 7.0 }, { x: 148.5, y: 68.2, w: 17.6, h: 21.8, rx: 7.0 }] },
  cometa: { key: "cometa", label: "Cometa", src: "/modules/blobs/cometa.png", eyeColor: "#15181C", eyes: [{ x: 107.5, y: 94.8, w: 15.7, h: 21.4, rx: 6.3 }, { x: 136.9, y: 94.8, w: 15.7, h: 21.4, rx: 6.3 }] },
  lila: { key: "lila", label: "Lila", src: "/modules/blobs/lila.png", eyeColor: "#15181C", eyes: [{ x: 104.8, y: 104.3, w: 14.1, h: 20.3, rx: 5.6 }, { x: 133.0, y: 104.3, w: 14.1, h: 20.3, rx: 5.6 }] },
  orbita: { key: "orbita", label: "Órbita", src: "/modules/blobs/orbita.png", eyeColor: "#060709", eyes: [{ x: 104.3, y: 96.7, w: 15.8, h: 18.7, rx: 6.3 }, { x: 135.9, y: 96.7, w: 15.8, h: 18.7, rx: 6.3 }] },
  caracol: { key: "caracol", label: "Caracol", src: "/modules/blobs/caracol.png", eyeColor: "#15181C", eyes: [{ x: 138.7, y: 109.4, w: 14.6, h: 17.1, rx: 5.9 }, { x: 170.2, y: 109.4, w: 14.6, h: 17.1, rx: 5.9 }] },
  iris: { key: "iris", label: "Iris", src: "/modules/blobs/iris.png", eyeColor: "#15181C", eyes: [{ x: 97.7, y: 106.6, w: 13.7, h: 20.3, rx: 5.5 }, { x: 125.1, y: 106.6, w: 13.7, h: 20.3, rx: 5.5 }] },
  laguna: { key: "laguna", label: "Laguna", src: "/modules/blobs/laguna.png", eyeColor: "#15181C", eyes: [{ x: 106.6, y: 83.8, w: 15.8, h: 18.5, rx: 6.3 }, { x: 138.1, y: 83.8, w: 15.8, h: 18.5, rx: 6.3 }] },
  carbon: { key: "carbon", label: "Carbón", src: "/modules/blobs/carbon.png", eyeColor: "#060709", eyes: [{ x: 93.7, y: 99.3, w: 16.3, h: 21.4, rx: 6.5 }, { x: 124.2, y: 99.3, w: 16.3, h: 21.4, rx: 6.5 }] },
};

export const BLOB_KEYS = Object.keys(BLOB_PRESETS);
export function isBlobKey(v?: string | null): v is string { return !!v && v in BLOB_PRESETS; }
