// AUTO-GENERATED by scripts/export_web_assets.py — do not edit by hand.
// Square blob bodies live in public/modules/blobs/<key>.png; eye rects are in the
// same 256x256 canvas and are drawn animated on top by <BlobAvatar>. An empty eye
// list = a 'cyclops' whose face is baked into the render (it bobs but doesn't blink).

export type BlobEye = { x: number; y: number; w: number; h: number; rx: number };
export type BlobPreset = { key: string; label: string; src: string; eyeColor: string; eyes: BlobEye[] };

export const BLOB_VIEWBOX = 256;

export const BLOB_PRESETS: Record<string, BlobPreset> = {
  menta: { key: "menta", label: "Menta", src: "/modules/blobs/menta.png", eyeColor: "#15181C", eyes: [{ x: 105.0, y: 93.1, w: 16.0, h: 33.8, rx: 6.4 }, { x: 135.0, y: 93.1, w: 16.0, h: 33.8, rx: 6.4 }] },
  parche: { key: "parche", label: "Parche", src: "/modules/blobs/parche.png", eyeColor: "#15181C", eyes: [{ x: 119.4, y: 88.6, w: 17.3, h: 33.8, rx: 6.9 }, { x: 151.9, y: 88.6, w: 17.3, h: 33.8, rx: 6.9 }] },
  trino: { key: "trino", label: "Trino", src: "/modules/blobs/trino.png", eyeColor: "#15181C", eyes: [{ x: 105.5, y: 130.1, w: 18.0, h: 29.7, rx: 7.2 }, { x: 141.5, y: 130.1, w: 18.0, h: 29.7, rx: 7.2 }] },
  cubi: { key: "cubi", label: "Cubi", src: "/modules/blobs/cubi.png", eyeColor: "#15181C", eyes: [{ x: 103.2, y: 93.1, w: 17.2, h: 33.8, rx: 6.9 }, { x: 135.6, y: 93.1, w: 17.2, h: 33.8, rx: 6.9 }] },
  nimbo: { key: "nimbo", label: "Nimbo", src: "/modules/blobs/nimbo.png", eyeColor: "#15181C", eyes: [{ x: 103.3, y: 93.1, w: 17.1, h: 33.8, rx: 6.9 }, { x: 135.6, y: 93.1, w: 17.1, h: 33.8, rx: 6.9 }] },
  papa: { key: "papa", label: "Papa", src: "/modules/blobs/papa.png", eyeColor: "#15181C", eyes: [{ x: 105.2, y: 90.9, w: 18.5, h: 30.5, rx: 7.4 }, { x: 141.3, y: 90.9, w: 18.5, h: 30.5, rx: 7.4 }] },
  noche: { key: "noche", label: "Noche", src: "/modules/blobs/noche.png", eyeColor: "#3AE7B0", eyes: [{ x: 105.0, y: 133.6, w: 15.9, h: 33.8, rx: 6.4 }, { x: 138.8, y: 133.6, w: 15.9, h: 33.8, rx: 6.4 }] },
  kiwi: { key: "kiwi", label: "Kiwi", src: "/modules/blobs/kiwi.png", eyeColor: "#15181C", eyes: [{ x: 109.1, y: 84.1, w: 13.1, h: 29.3, rx: 5.2 }, { x: 133.8, y: 84.1, w: 13.1, h: 29.3, rx: 5.2 }] },
  gajo: { key: "gajo", label: "Gajo", src: "/modules/blobs/gajo.png", eyeColor: "#15181C", eyes: [{ x: 107.9, y: 95.3, w: 16.6, h: 29.3, rx: 6.7 }, { x: 139.3, y: 95.3, w: 16.6, h: 29.3, rx: 6.7 }] },
  campana: { key: "campana", label: "Campana", src: "/modules/blobs/campana.png", eyeColor: "#15181C", eyes: [{ x: 108.6, y: 86.3, w: 15.8, h: 29.3, rx: 6.3 }, { x: 135.5, y: 86.3, w: 15.8, h: 29.3, rx: 6.3 }] },
  cobalto: { key: "cobalto", label: "Cobalto", src: "/modules/blobs/cobalto.png", eyeColor: "#15181C", eyes: [{ x: 107.7, y: 95.3, w: 16.8, h: 29.3, rx: 6.7 }, { x: 139.4, y: 95.3, w: 16.8, h: 29.3, rx: 6.7 }] },
  rubi: { key: "rubi", label: "Rubí", src: "/modules/blobs/rubi.png", eyeColor: "#15181C", eyes: [] },
  trebol: { key: "trebol", label: "Trébol", src: "/modules/blobs/trebol.png", eyeColor: "#15181C", eyes: [{ x: 102.6, y: 120.1, w: 17.2, h: 29.3, rx: 6.9 }, { x: 134.1, y: 120.1, w: 17.2, h: 29.3, rx: 6.9 }] },
  saturno: { key: "saturno", label: "Saturno", src: "/modules/blobs/saturno.png", eyeColor: "#15181C", eyes: [] },
  onyx: { key: "onyx", label: "Onyx", src: "/modules/blobs/onyx.png", eyeColor: "#3AE7B0", eyes: [{ x: 96.3, y: 124.6, w: 16.6, h: 29.3, rx: 6.6 }, { x: 129.5, y: 124.6, w: 16.6, h: 29.3, rx: 6.6 }] },
};

export const BLOB_KEYS = Object.keys(BLOB_PRESETS);
export function isBlobKey(v?: string | null): v is string { return !!v && v in BLOB_PRESETS; }
