// AUTO-GENERATED by scripts/export_android_mascot_assets.py — do not edit by hand.
package dev.agentprojectcontext.apx;

import android.graphics.Color;

final class MascotBlobCatalog {
    static final String DEFAULT_KEY = "noche";

    static final class Preset {
        final String key;
        final int drawable;
        final int eyeColor;
        final float[][] eyes;

        Preset(String key, int drawable, int eyeColor, float[][] eyes) {
            this.key = key;
            this.drawable = drawable;
            this.eyeColor = eyeColor;
            this.eyes = eyes;
        }
    }

    static Preset forKey(String value) {
        String key = value == null ? DEFAULT_KEY : value.trim();
        return switch (key) {
            case "menta" -> new Preset("menta", R.drawable.mascot_menta, Color.parseColor("#15181C"), new float[][]{new float[]{121.9f, 93.1f, 16.0f, 33.8f, 6.4f}, new float[]{151.9f, 93.1f, 16.0f, 33.8f, 6.4f}});
            case "parche" -> new Preset("parche", R.drawable.mascot_parche, Color.parseColor("#15181C"), new float[][]{new float[]{133.6f, 88.6f, 17.3f, 33.8f, 6.9f}, new float[]{166.1f, 88.6f, 17.3f, 33.8f, 6.9f}});
            case "trino" -> new Preset("trino", R.drawable.mascot_trino, Color.parseColor("#15181C"), new float[][]{new float[]{105.5f, 130.1f, 18.0f, 29.7f, 7.2f}, new float[]{141.5f, 130.1f, 18.0f, 29.7f, 7.2f}});
            case "cubi" -> new Preset("cubi", R.drawable.mascot_cubi, Color.parseColor("#15181C"), new float[][]{new float[]{103.2f, 93.1f, 17.2f, 33.8f, 6.9f}, new float[]{135.6f, 93.1f, 17.2f, 33.8f, 6.9f}});
            case "nimbo" -> new Preset("nimbo", R.drawable.mascot_nimbo, Color.parseColor("#15181C"), new float[][]{new float[]{103.3f, 93.1f, 17.1f, 33.8f, 6.9f}, new float[]{135.6f, 93.1f, 17.1f, 33.8f, 6.9f}});
            case "papa" -> new Preset("papa", R.drawable.mascot_papa, Color.parseColor("#15181C"), new float[][]{new float[]{125.5f, 90.9f, 18.5f, 30.5f, 7.4f}, new float[]{161.6f, 90.9f, 18.5f, 30.5f, 7.4f}});
            case "noche" -> new Preset("noche", R.drawable.mascot_noche, Color.parseColor("#3AE7B0"), new float[][]{new float[]{123.8f, 133.6f, 15.9f, 33.8f, 6.4f}, new float[]{157.6f, 133.6f, 15.9f, 33.8f, 6.4f}});
            case "kiwi" -> new Preset("kiwi", R.drawable.mascot_kiwi, Color.parseColor("#15181C"), new float[][]{new float[]{123.0f, 84.1f, 13.1f, 29.3f, 5.2f}, new float[]{147.7f, 84.1f, 13.1f, 29.3f, 5.2f}});
            case "gajo" -> new Preset("gajo", R.drawable.mascot_gajo, Color.parseColor("#15181C"), new float[][]{new float[]{107.9f, 95.3f, 16.6f, 29.3f, 6.7f}, new float[]{139.3f, 95.3f, 16.6f, 29.3f, 6.7f}});
            case "campana" -> new Preset("campana", R.drawable.mascot_campana, Color.parseColor("#15181C"), new float[][]{new float[]{108.6f, 86.3f, 15.8f, 29.3f, 6.3f}, new float[]{135.5f, 86.3f, 15.8f, 29.3f, 6.3f}});
            case "cobalto" -> new Preset("cobalto", R.drawable.mascot_cobalto, Color.parseColor("#15181C"), new float[][]{new float[]{125.5f, 95.3f, 16.8f, 29.3f, 6.7f}, new float[]{157.2f, 95.3f, 16.8f, 29.3f, 6.7f}});
            case "rubi" -> new Preset("rubi", R.drawable.mascot_rubi, Color.parseColor("#15181C"), new float[][]{new float[]{123.0f, 84.1f, 13.1f, 29.3f, 5.2f}, new float[]{147.7f, 84.1f, 13.1f, 29.3f, 5.2f}});
            case "trebol" -> new Preset("trebol", R.drawable.mascot_trebol, Color.parseColor("#15181C"), new float[][]{new float[]{123.6f, 120.1f, 17.2f, 29.3f, 6.9f}, new float[]{155.1f, 120.1f, 17.2f, 29.3f, 6.9f}});
            case "saturno" -> new Preset("saturno", R.drawable.mascot_saturno, Color.parseColor("#15181C"), new float[][]{});
            case "onyx" -> new Preset("onyx", R.drawable.mascot_onyx, Color.parseColor("#3AE7B0"), new float[][]{new float[]{119.7f, 124.6f, 16.6f, 29.3f, 6.6f}, new float[]{152.9f, 124.6f, 16.6f, 29.3f, 6.6f}});
            case "perla" -> new Preset("perla", R.drawable.mascot_perla, Color.parseColor("#15181C"), new float[][]{new float[]{121.4f, 108.4f, 13.5f, 21.4f, 5.4f}, new float[]{148.5f, 108.4f, 13.5f, 21.4f, 5.4f}});
            case "faro" -> new Preset("faro", R.drawable.mascot_faro, Color.parseColor("#15181C"), new float[][]{new float[]{94.4f, 100.0f, 14.2f, 20.3f, 5.7f}, new float[]{122.7f, 100.0f, 14.2f, 20.3f, 5.7f}});
            case "brasa" -> new Preset("brasa", R.drawable.mascot_brasa, Color.parseColor("#15181C"), new float[][]{new float[]{94.8f, 95.2f, 16.9f, 18.6f, 6.8f}, new float[]{126.3f, 95.2f, 16.9f, 18.6f, 6.8f}});
            case "aqua" -> new Preset("aqua", R.drawable.mascot_aqua, Color.parseColor("#15181C"), new float[][]{new float[]{92.9f, 105.8f, 10.9f, 20.3f, 4.4f}, new float[]{114.7f, 105.8f, 10.9f, 20.3f, 4.4f}});
            case "coral" -> new Preset("coral", R.drawable.mascot_coral, Color.parseColor("#15181C"), new float[][]{new float[]{99.4f, 147.0f, 14.5f, 19.1f, 5.8f}, new float[]{129.3f, 147.0f, 14.5f, 19.1f, 5.8f}});
            case "zafiro" -> new Preset("zafiro", R.drawable.mascot_zafiro, Color.parseColor("#15181C"), new float[][]{new float[]{105.7f, 116.5f, 14.3f, 21.4f, 5.7f}, new float[]{132.4f, 116.5f, 14.3f, 21.4f, 5.7f}});
            case "pino" -> new Preset("pino", R.drawable.mascot_pino, Color.parseColor("#15181C"), new float[][]{new float[]{125.0f, 123.2f, 13.4f, 20.3f, 5.4f}, new float[]{151.9f, 123.2f, 13.4f, 20.3f, 5.4f}});
            case "eclipse" -> new Preset("eclipse", R.drawable.mascot_eclipse, Color.parseColor("#060709"), new float[][]{new float[]{102.8f, 111.9f, 15.5f, 20.3f, 6.2f}, new float[]{131.5f, 111.9f, 15.5f, 20.3f, 6.2f}});
            case "peon" -> new Preset("peon", R.drawable.mascot_peon, Color.parseColor("#15181C"), new float[][]{new float[]{109.1f, 85.6f, 10.2f, 18.0f, 4.1f}, new float[]{132.9f, 85.6f, 10.2f, 18.0f, 4.1f}});
            case "ovni" -> new Preset("ovni", R.drawable.mascot_ovni, Color.parseColor("#15181C"), new float[][]{new float[]{106.6f, 105.0f, 15.8f, 16.0f, 6.3f}, new float[]{138.1f, 105.0f, 15.8f, 16.0f, 6.3f}});
            case "amatista" -> new Preset("amatista", R.drawable.mascot_amatista, Color.parseColor("#15181C"), new float[][]{new float[]{85.8f, 103.4f, 16.9f, 18.3f, 6.8f}, new float[]{117.3f, 103.4f, 16.9f, 18.3f, 6.8f}});
            case "volcan" -> new Preset("volcan", R.drawable.mascot_volcan, Color.parseColor("#15181C"), new float[][]{new float[]{100.6f, 97.4f, 13.4f, 19.1f, 5.4f}, new float[]{127.5f, 97.4f, 13.4f, 19.1f, 5.4f}});
            case "quad" -> new Preset("quad", R.drawable.mascot_quad, Color.parseColor("#15181C"), new float[][]{new float[]{80.9f, 68.2f, 17.6f, 21.8f, 7.0f}, new float[]{148.5f, 68.2f, 17.6f, 21.8f, 7.0f}});
            case "cometa" -> new Preset("cometa", R.drawable.mascot_cometa, Color.parseColor("#15181C"), new float[][]{new float[]{107.5f, 94.8f, 15.7f, 21.4f, 6.3f}, new float[]{136.9f, 94.8f, 15.7f, 21.4f, 6.3f}});
            case "lila" -> new Preset("lila", R.drawable.mascot_lila, Color.parseColor("#15181C"), new float[][]{new float[]{104.8f, 104.3f, 14.1f, 20.3f, 5.6f}, new float[]{133.0f, 104.3f, 14.1f, 20.3f, 5.6f}});
            case "orbita" -> new Preset("orbita", R.drawable.mascot_orbita, Color.parseColor("#060709"), new float[][]{new float[]{104.3f, 96.7f, 15.8f, 18.7f, 6.3f}, new float[]{135.9f, 96.7f, 15.8f, 18.7f, 6.3f}});
            case "caracol" -> new Preset("caracol", R.drawable.mascot_caracol, Color.parseColor("#15181C"), new float[][]{new float[]{149.9f, 109.4f, 14.6f, 17.1f, 5.9f}, new float[]{181.4f, 109.4f, 14.6f, 17.1f, 5.9f}});
            case "iris" -> new Preset("iris", R.drawable.mascot_iris, Color.parseColor("#15181C"), new float[][]{new float[]{97.7f, 106.6f, 13.7f, 20.3f, 5.5f}, new float[]{125.1f, 106.6f, 13.7f, 20.3f, 5.5f}});
            case "laguna" -> new Preset("laguna", R.drawable.mascot_laguna, Color.parseColor("#15181C"), new float[][]{new float[]{106.6f, 83.8f, 15.8f, 18.5f, 6.3f}, new float[]{138.1f, 83.8f, 15.8f, 18.5f, 6.3f}});
            case "carbon" -> new Preset("carbon", R.drawable.mascot_carbon, Color.parseColor("#060709"), new float[][]{new float[]{93.7f, 99.3f, 16.3f, 21.4f, 6.5f}, new float[]{124.2f, 99.3f, 16.3f, 21.4f, 6.5f}});
            default -> forKey(DEFAULT_KEY);
        };
    }

    private MascotBlobCatalog() {}
}
