"""Mirror generated web blob presets into the native Android mascot.

The web registry remains the visual source of truth. Android bundles the same
body PNGs and a generated Java catalog so its Canvas renderer can draw the same
eyes without network access.
"""
from __future__ import annotations

import pathlib
import re
import shutil


REPO = pathlib.Path(__file__).resolve().parents[1]
PRESETS = REPO / "src/interfaces/web/src/components/agents/blobPresets.ts"
WEB_BODIES = REPO / "src/interfaces/web/public/modules/blobs"
ANDROID_RES = REPO / "src/interfaces/android/app/src/main/res/drawable-nodpi"
JAVA_OUT = REPO / "src/interfaces/android/app/src/main/java/dev/agentprojectcontext/apx/MascotBlobCatalog.java"

LINE = re.compile(
    r'^\s{2}(\w+):\s*\{.*?eyeColor:\s*"(#[0-9A-Fa-f]{6})",\s*eyes:\s*\[(.*)]\s*},$'
)
EYE = re.compile(
    r"\{\s*x:\s*([\d.]+),\s*y:\s*([\d.]+),\s*w:\s*([\d.]+),\s*h:\s*([\d.]+),\s*rx:\s*([\d.]+)\s*}"
)


def read_presets() -> list[tuple[str, str, list[tuple[str, ...]]]]:
    result = []
    for line in PRESETS.read_text(encoding="utf-8").splitlines():
        match = LINE.match(line)
        if not match:
            continue
        key, color, raw_eyes = match.groups()
        result.append((key, color, EYE.findall(raw_eyes)))
    if not result:
        raise RuntimeError("No blob presets found")
    return result


def java_source(presets: list[tuple[str, str, list[tuple[str, ...]]]]) -> str:
    cases = []
    for key, color, eyes in presets:
        eye_rows = ", ".join(
            "new float[]{" + ", ".join(f"{value}f" for value in eye) + "}"
            for eye in eyes
        )
        cases.append(
            f'            case "{key}" -> new Preset("{key}", R.drawable.mascot_{key}, '
            f'Color.parseColor("{color}"), new float[][]{{{eye_rows}}});'
        )
    return "\n".join([
        "// AUTO-GENERATED by scripts/export_android_mascot_assets.py — do not edit by hand.",
        "package dev.agentprojectcontext.apx;",
        "",
        "import android.graphics.Color;",
        "",
        "final class MascotBlobCatalog {",
        "    static final String DEFAULT_KEY = \"noche\";",
        "",
        "    static final class Preset {",
        "        final String key;",
        "        final int drawable;",
        "        final int eyeColor;",
        "        final float[][] eyes;",
        "",
        "        Preset(String key, int drawable, int eyeColor, float[][] eyes) {",
        "            this.key = key;",
        "            this.drawable = drawable;",
        "            this.eyeColor = eyeColor;",
        "            this.eyes = eyes;",
        "        }",
        "    }",
        "",
        "    static Preset forKey(String value) {",
        "        String key = value == null ? DEFAULT_KEY : value.trim();",
        "        return switch (key) {",
        *cases,
        "            default -> forKey(DEFAULT_KEY);",
        "        };",
        "    }",
        "",
        "    private MascotBlobCatalog() {}",
        "}",
        "",
    ])


def main() -> None:
    presets = read_presets()
    ANDROID_RES.mkdir(parents=True, exist_ok=True)
    for key, _color, _eyes in presets:
        shutil.copyfile(WEB_BODIES / f"{key}.png", ANDROID_RES / f"mascot_{key}.png")
    JAVA_OUT.write_text(java_source(presets), encoding="utf-8")
    print(f"wrote {len(presets)} Android mascot presets")


if __name__ == "__main__":
    main()
