"""Export square blob bodies (no eyes) + a TS preset registry for the web app.
Eyes are drawn animated on top in the browser; here we only compute the eye
rects in the same 256x256 canvas the body is padded into. A preset with an
empty eye list is a 'cyclops' whose face is baked into the render (keeps its
ring/LED); it still bobs, it just doesn't blink."""
from PIL import Image
import os
import pathlib

# Repo root is the script's parent directory (scripts/ -> repo). No hardcoded
# local paths. Source crops (blob_<key>.png) are read from BLOB_SRC_DIR, which
# defaults to the current working directory but can be overridden via env.
REPO = pathlib.Path(__file__).resolve().parents[1]
PUB = REPO / "src/interfaces/web/public/modules/blobs"
TS = REPO / "src/interfaces/web/src/components/agents/blobPresets.ts"
SCRATCH = pathlib.Path(os.environ.get("BLOB_SRC_DIR", "."))
SIZE = 256
PAD = 0.06

# key: (label, eyeColor, eyes)  where eyes = (cxl, cxr, cy, ew_frac, eh_frac) | None
BLOBS = {
    # ── original 7 ──
    "menta":   ("Menta",   "#15181C", (0.42, 0.58, 0.42, 0.085, 0.15)),
    "parche":  ("Parche",  "#15181C", (0.50, 0.66, 0.40, 0.085, 0.15)),
    "trino":   ("Trino",   "#15181C", (0.44, 0.60, 0.58, 0.080, 0.14)),
    "cubi":    ("Cubi",    "#15181C", (0.42, 0.58, 0.42, 0.085, 0.15)),
    "nimbo":   ("Nimbo",   "#15181C", (0.42, 0.58, 0.42, 0.085, 0.15)),
    "papa":    ("Papa",    "#15181C", (0.44, 0.60, 0.40, 0.082, 0.14)),
    "noche":   ("Noche",   "#3AE7B0", (0.42, 0.60, 0.60, 0.085, 0.15)),
    # ── new 8 ──
    "kiwi":    ("Kiwi",    "#15181C", (0.42, 0.58, 0.37, 0.085, 0.13)),
    "gajo":    ("Gajo",    "#15181C", (0.44, 0.60, 0.42, 0.085, 0.13)),
    "campana": ("Campana", "#15181C", (0.44, 0.58, 0.38, 0.082, 0.13)),
    "cobalto": ("Cobalto", "#15181C", (0.44, 0.60, 0.42, 0.085, 0.13)),
    "rubi":    ("Rubí",    "#15181C", None),
    "trebol":  ("Trébol",  "#15181C", (0.42, 0.57, 0.53, 0.082, 0.13)),
    "saturno": ("Saturno", "#15181C", None),
    "onyx":    ("Onyx",    "#3AE7B0", (0.38, 0.55, 0.55, 0.085, 0.13)),
}

def eye_rects(W, H, sc, offx, offy, e):
    if e is None:
        return []
    cxl, cxr, cy, ewf, ehf = e
    ew, eh = ewf * W * sc, ehf * H * sc
    r = min(ew, eh) * 0.40
    out = []
    for cx in (cxl, cxr):
        ccx, ccy = offx + cx * W * sc, offy + cy * H * sc
        out.append((round(ccx - ew / 2, 1), round(ccy - eh / 2, 1), round(ew, 1), round(eh, 1), round(r, 1)))
    return out

presets = {}
for k, (label, color, e) in BLOBS.items():
    im = Image.open(SCRATCH / f"blob_{k}.png").convert("RGBA")
    W, H = im.size
    box = SIZE * (1 - 2 * PAD)
    sc = min(box / W, box / H)
    nw, nh = W * sc, H * sc
    offx, offy = (SIZE - nw) / 2, (SIZE - nh) / 2
    canvas = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    canvas.alpha_composite(im.resize((max(1, round(nw)), max(1, round(nh))), Image.LANCZOS), (round(offx), round(offy)))
    canvas.save(PUB / f"{k}.png")
    presets[k] = (label, f"/modules/blobs/{k}.png", color, eye_rects(W, H, sc, offx, offy, e))
    print(f"{k}: body ok, {len(presets[k][3])} eyes")

lines = [
    "// AUTO-GENERATED by scripts/export_web_assets.py — do not edit by hand.",
    "// Square blob bodies live in public/modules/blobs/<key>.png; eye rects are in the",
    "// same 256x256 canvas and are drawn animated on top by <BlobAvatar>. An empty eye",
    "// list = a 'cyclops' whose face is baked into the render (it bobs but doesn't blink).",
    "",
    "export type BlobEye = { x: number; y: number; w: number; h: number; rx: number };",
    "export type BlobPreset = { key: string; label: string; src: string; eyeColor: string; eyes: BlobEye[] };",
    "",
    "export const BLOB_VIEWBOX = 256;",
    "",
    "export const BLOB_PRESETS: Record<string, BlobPreset> = {",
]
for k, (label, src, color, eyes) in presets.items():
    ev = ", ".join(f"{{ x: {x}, y: {y}, w: {w}, h: {h}, rx: {r} }}" for (x, y, w, h, r) in eyes)
    lines.append(f'  {k}: {{ key: "{k}", label: "{label}", src: "{src}", eyeColor: "{color}", eyes: [{ev}] }},')
lines += [
    "};",
    "",
    "export const BLOB_KEYS = Object.keys(BLOB_PRESETS);",
    "export function isBlobKey(v?: string | null): v is string { return !!v && v in BLOB_PRESETS; }",
    "",
]
TS.write_text("\n".join(lines), encoding="utf-8")
print("wrote", TS, "with", len(presets), "presets")
